# Generated by Django 5.1.4 on 2025-01-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_alter_inward_quantity_issuematerial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuematerial',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
