# Generated by Django 5.1.4 on 2025-01-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_materialconsumption_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialconsumption',
            name='remarks',
            field=models.TextField(blank=True, default='NULL', null=True),
        ),
    ]
