# Generated by Django 5.1.4 on 2025-01-22 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_alter_materialconsumption_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inward',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inward', to='warehouse.material'),
        ),
        migrations.AlterField(
            model_name='materialconsumption',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
