# Generated by Django 5.1.4 on 2025-01-22 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_alter_inward_material_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='quantity',
        ),
        migrations.AddField(
            model_name='inventory',
            name='available_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='inward_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='issued_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.building'),
        ),
    ]
