# Generated by Django 5.1.4 on 2025-01-24 10:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_remove_inventory_last_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='company',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
